module.exports = {

    GET_STARTED: 'GET_STARTED',

    SUBSCRIBE_TO_NOTIFICATIONS: 'SUBSCRIBE_TO_NOTIFICATIONS',
    UNSUBSCRIBE_TO_NOTIFICATIONS: 'UNSUBSCRIBE_TO_NOTIFICATIONS',
    BLOCK_DRIVER: 'BLOCK_DRIVER',
    MESSAGE_DRIVER: 'MESSAGE_DRIVER',
    GET_HELP: 'GET_HELP',

    RECEIVE_NOTIFICATIONS_YES: 'RECEIVE_NOTIFICATIONS_YES',
    RECEIVE_NOTIFICATIONS_NO: 'RECEIVE_NOTIFICATIONS_NO',

    MESSAGE_DRIVER_YES: 'MESSAGE_DRIVER_YES',
    MESSAGE_DRIVER_NO: 'MESSAGE_DRIVER_NO'
};